ALTER TABLE ND_FIRM ADD PASSWORD VARCHAR2(100);

CREATE TABLE RESPONSES (
  ID NUMBER PRIMARY KEY,
  ZAM_ID NUMBER NOT NULL,
  FIRM_ID NUMBER NOT NULL,
  TEXT VARCHAR2(1000),
  CREATED_AT DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(20) DEFAULT 'pending',
  FROM_TYPE VARCHAR2(20) DEFAULT 'company',
  CONSTRAINT RESPONSES_REQUEST_FK FOREIGN KEY (ZAM_ID) REFERENCES BASE_MAIN(ID),
  CONSTRAINT RESPONSES_FIRM_FK FOREIGN KEY (FIRM_ID) REFERENCES ND_FIRM(FIRM_ID)
);
